apps/user_messages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<user_id>\d+)$', views.show_user, name = 'show_user'),
    url(r'^(?P<user_id>\d+)/post_message$', views.post_message, name = 'post_message'),
    url(r'^(?P<user_id>\d+)/delete/(?P<message_id>\d+)$', views.delete_message, name = 'delete_message'),
    url(r'^(?P<message_id>\d+)/(?P<user_id>\d+)/post_comment$', views.post_comment, name = 'post_comment'),
    url(r'^(?P<user_id>\d+)/delete_comment/(?P<comment_id>\d+)$', views.delete_comment, name = 'delete_comment')
]

user_dashboard_assignment/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^users/show/', include('apps.user_messages.urls', namespace ='messages')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.user_dashboard.urls', namespace = 'dashboard'))
]

apps/user_messages/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..user_dashboard.models import User

class MessageManager(models.Manager):
    def validate_post_message(self, data, session, user_id):
        errors = []
        validation = {
            'success' : False,
            'result'  : None,
            'from'    : 'message'
        }
        if len(data['text']) < 1:
            errors.append('Message text is required')
        if not errors:
            try:
                message_to = User.objects.get(id = user_id)
                if message_to.id == session['current_user_id']:
                    raise Exception
                message_from = User.objects.get(id = session['current_user_id'])
                message = self.create(
                    text = data['text'],
                    message_to = message_to,
                    message_from = message_from
                )
                validation['success'] = True
                validation['result'] = message
            except:
                errors =['shit went wrong']
                validation['result'] = errors
        else:
            validation['result'] = errors
        return validation
    def validate_delete_message(self, session, message_id):
        errors = []
        validation = {
            'success' : False,
            'result'  : None
        }
        message = self.get(id = message_id)
        # make sure the form action url wasn't tampered with to delete someone elses post
        if message.message_from.id != session['current_user_id']:
            errors.append('hacker')
        if not errors:
            message.delete()
            validation['success'] = True
        return validation


class CommentManager(models.Manager):
    def validate_post_comment(self, data, session, message_id, user_id):
        errors = []
        validation = {
            'success' : False,
            'result'  : None,
            'from'    : 'comment'
        }
        if len(data['text']) < 1:
            errors.append('Comment text is required')
        if not errors:
            try:
                message = Message.objects.get(id = message_id)
                user = User.objects.get(id = session['current_user_id'])
                comment = self.create(
                    text = data['text'],
                    comment_on = message,
                    comment_by = user
                )
                validation['success'] = True
                validation['result'] = comment
            except:
                pass
        else:
            validation['result'] = errors
        return validation
    
    def validate_delete_comment(self, session, comment_id):
        errors = []
        validation = {
            'success' : False,
            'result'  : None
        }
        comment = self.get(id = comment_id)
        if comment.comment_by.id != session['current_user_id']:
            errors.append('Hacker')
        if not errors:
            comment.delete()
            validation['success'] = True
        return validation

class Message(models.Model):
    text = models.TextField()

    message_from = models.ForeignKey(User, related_name = 'messages_sent')
    message_to = models.ForeignKey(User, related_name = 'messages_received')

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    objects = MessageManager()

class Comment(models.Model):
    text = models.TextField()

    comment_on = models.ForeignKey(Message, related_name = 'comments')
    comment_by = models.ForeignKey(User, related_name = 'comments')

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    objects = CommentManager()

apps/user_messages/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import Message, Comment 
from ..user_dashboard.models import User
from ..user_dashboard import my_utils as _
def index(request):
    return redirect('messages:show_user', user_id = request.session['current_user_id'])

def show_user(request, user_id):
    user = User.objects.get(id = user_id)
    messages = user.messages_received.all().order_by('-created_at')
    threads = [ (message, message.comments.all().order_by('created_at')) for message in messages ]
    context = {
        'user' : user,
        'threads': threads
    }
    return render(request, 'user_messages/show_user.html', context)

@_.if_not_POST('messages:index')
def post_message(request, user_id):
    validation = Message.objects.validate_post_message(request.POST, request.session, user_id)
    if validation['success']:
        return redirect('messages:show_user', user_id = user_id)

@_.if_not_POST('messages:index')
def delete_message(request, user_id, message_id):
    validation = Message.objects.validate_delete_message(request.session, message_id)
    if validation['success']:
        return redirect('messages:show_user', user_id = user_id)

@_.if_not_POST('messages:index')
def post_comment(request, message_id, user_id):
    validation = Comment.objects.validate_post_comment(request.POST, request.session, message_id, user_id)
    if validation['success']:
        return redirect('messages:show_user', user_id = user_id)

@_.if_not_POST('messages:index')
def delete_comment(request, user_id, comment_id):
    validation = Comment.objects.validate_delete_comment(request.session, comment_id)
    if validation['success']:
        return redirect('messages:show_user', user_id = user_id)

apps/user_messages/templates/user_messages/show_user.html
{% extends 'user_dashboard/base.html' %}
{% block title %}{{user.first_name}} {{user.last_name}}{% endblock %}
{% block description %}Messaging page for {{user.first_name}}{% endblock %}
{% block extra_styles %}
	{% load static %}
	<link rel="stylesheet" href="{% static 'user_messages/css/style.css' %}">
{% endblock extra_styles %}
{% block main %}
{% load tz %}
{% timezone "America/Los_Angeles" %}
<div class="row">
	<h1>{{user.first_name}}</h1>
	<ul class="user-info">
		<li>Registered at: {{user.created_at}}</li>
		<li>ID: {{user.id}}</li>
		<li>E-Mail Address: {{user.email}}</li>
		<li>Description: {{user.description}}</li>
	</ul>
</div>
{% if request.session.current_user_id != user.id %}
<div class="row">
	<form action="{% url 'messages:post_message' user_id=user.id %}" method="POST">
		{% csrf_token %}
		<label for="text">
		<textarea name="text" placeholder="Leave a message for {{user.first_name}}"></textarea> 
		<button type="submit">Post Message</button>
	</form>
</div>
{% endif %}
<div class="row">
{% for message, comments in threads %}
	<div class="message">
		<h4>{{message.message_from.first_name}} said at {{message.created_at}}:</h4>
		<p>{{message.text}}</p>
		{% if message.message_from.id == request.session.current_user_id %}
		<form action="{% url 'messages:delete_message' user_id=user.id message_id=message.id %}" method="POST">
			{% csrf_token %}
			<input type="submit" value="delete">
		</form>
		{% endif %}
	</div>
	<div class="comments">
		{% for comment in comments %}
		{% with id=comment.comment_by.id %}
		<div class="row">
			<div class="comment nine columns">
				<h5>{{comment.comment_by.first_name}} said at {{comment.created_at}}:</h5>
				<p>{{comment.text}}</p>
			</div>
			{% if comment.comment_by.id == request.session.current_user_id %}
			<div class="comment-actions three columns">
				<form action="{% url 'messages:delete_comment' user_id=user.id comment_id=comment.id %}" method="POST">
					{% csrf_token %}
					<button type="submit">Delete</button>
				</form>
			</div>
			{% endif %}
		</div>
		{% endwith %}
		{% endfor %}
		<div class="row">
		<div class="nine columns">
		<form action="{% url 'messages:post_comment' message_id=message.id user_id=user.id %}" method="POST">
			{% csrf_token %}
			<textarea name="text" placeholder="Write a comment"></textarea>
			<button type="submit">Add comment</button>
		</form>
		</div>
		</div>
	</div>
{% endfor %}
</div>
{% endtimezone %}
{% endblock %}