apps/user_dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',                 views.index,            name = 'index'),
    url(r'^signin$',           views.signin,           name = 'signin'),
    url(r'^signin/process$',   views.signin_process,   name = 'signin_process'),
    url(r'^signout$',          views.signout,          name = 'signout'),
    url(r'^register$',         views.register,         name = 'register'),
    url(r'^register/process$', views.register_process, name = 'register_process'),
    url(r'^dashboard$',        views.dashboard,        name = 'dashboard'),
    url(r'^users$',            views.users,            name = 'users'),
    url(r'^users/new$',        views.new_user,         name = 'new_user'),
    url(r'^users/new/process$',  views.user_new_process, name = 'user_new_process'),
    url(r'^users/edit$',         views.edit_user,        name = 'edit_user'),
    url(r'^users/edit/(?P<user_id>\d+)$',                    views.admin_edit_user,          name = 'admin_edit_user'),
    url(r'^users/edit/(?P<user_id>\d+)/info/process$',       views.edit_info_process,        name = 'edit_info_process'),
    url(r'^users/edit/(?P<user_id>\d+)/password/process$',   views.edit_password_process,    name = 'edit_password_process'),
    url(r'^users/edit/(?P<user_id>\d+)/description/process$',views.edit_description_process, name = 'edit_description_process'),
    url(r'^users/(?P<user_id>\d+)/remove$',                  views.admin_remove_user,        name = 'admin_remove_user')
]

apps/user_messages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<user_id>\d+)$', views.show_user, name = 'show_user'),
    url(r'^(?P<user_id>\d+)/post_message$', views.post_message, name = 'post_message'),
    url(r'^(?P<user_id>\d+)/delete/(?P<message_id>\d+)$', views.delete_message, name = 'delete_message'),
    url(r'^(?P<message_id>\d+)/(?P<user_id>\d+)/post_comment$', views.post_comment, name = 'post_comment'),
    url(r'^(?P<user_id>\d+)/delete_comment/(?P<comment_id>\d+)$', views.delete_comment, name = 'delete_comment')
]

user_dashboard_assignment/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^users/show/', include('apps.user_messages.urls', namespace ='messages')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.user_dashboard.urls', namespace = 'dashboard'))
]

apps/user_dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User
# contains decorators logged_in_redirect, not_logged_in_redirect, if_not_POST
import my_utils as _


# used as decorator so logged in users can't go to start page, register page, or login page
logged_in_redirect = _.user_redirect('current_user_id', 'dashboard:dashboard')
# used as decorator so typing in urls without being logged in redirects out
# 
not_logged_in_redirect = _.no_user_redirect('current_user_id', 'dashboard:index')

@logged_in_redirect
def index(request):
    return render(request, 'user_dashboard/index.html')

@logged_in_redirect
def signin(request):
    return render(request, 'user_dashboard/signin.html')

@_.if_not_POST('dashboard:signin')
def signin_process(request):
    validation = User.objects.validate_signin_form(request.POST)
    if validation['success']:
        request.session['current_user_id'] = validation['result'].id
        request.session['current_user_is_admin'] = True if validation['result'].privileges else False
        return redirect('dashboard:dashboard')
    else:
        for error in validation['result']:
            messages.add_message(
            request,
            messages.ERROR,
            error,
            extra_tags = validation['from'])
        return redirect('dashboard:signin')

@logged_in_redirect
def register(request):
    return render(request, 'user_dashboard/register.html')

@_.if_not_POST('dashboard:register')
def register_process(request):
    validation = User.objects.validate_register_form(request.POST)
    if validation['success']:
        request.session['current_user_id'] = validation['result'].id
        request.session['current_user_is_admin'] = True if validation['result'].privileges else False
        return redirect('dashboard:dashboard')
    else:
        for error in validation['result']:
            messages.add_message(
                request,
                messages.ERROR,
                error,
                extra_tags = validation['from'])
        return redirect('dashboard:register')

@not_logged_in_redirect
def signout(request):
    if 'current_user_id' in request.session.keys():
        del request.session['current_user_id']
    if 'current_user_is_admin' in request.session.keys():
        del request.session['current_user_is_admin']
    return render(request, 'user_dashboard/signout.html')

@not_logged_in_redirect
def dashboard(request):
    users = User.objects.all()
    if not request.session['current_user_is_admin']:
        users = users.filter(is_visible=True)
    context = {
        'users' : users
    }
    return render(request, 'user_dashboard/dashboard.html', context)

@not_logged_in_redirect
def users(request):
    return redirect('dashboard:dashboard')

@not_logged_in_redirect
def new_user(request):
    return render(request, 'user_dashboard/new_user.html') 

@_.if_not_POST('dashboard:new_user')
def user_new_process(request):
    validation = User.objects.admin_validate_add_form(request.POST)
    if validation['success']:
        messages.add_message(request, messages.INFO, 'User added successfully')
        return redirect('dashboard:new_user')
    else:
        for error in validation['result']:
            messages.add_message(request, messages.ERROR, error)
        return redirect('dashboard:new_user')

@not_logged_in_redirect
def edit_user(request): 
    context = {
        'user' : User.objects.get(id = request.session['current_user_id'])
        }
    return render(request, 'user_dashboard/edit_user.html', context)

@_.if_not_POST('dashboard:edit_user')
def edit_info_process(request, user_id):
    validation = User.objects.validate_info_edit_form(request.POST, user_id)
    if validation['success']:
        messages.add_message(
            request, 
            messages.INFO,
            'User info updated successfully',
            extra_tags = 'general')
    else:
        for error in validation['result']:
            messages.add_message(
                request,
                messages.ERROR,
                error,
                extra_tags = validation['from'])
    return redirect('dashboard:edit_user')

@_.if_not_POST('dashboard:edit_user')
def edit_password_process(request, user_id):
    validation = User.objects.validate_password_edit_form(request.POST, user_id)
    if validation['success']:
        messages.add_message(
            request,
            messages.INFO,
            'Password updated successfully',
            extra_tags = 'general')
    else:
        for error in validation['result']:
            messages.add_message(
                request,
                messages.ERROR,
                error,
                extra_tags = validation['from'])
    return redirect('dashboard:edit_user')

@_.if_not_POST('dashboard:edit_user')
def edit_description_process(request, user_id):
    validation = User.objects.validate_description_edit_form(request.POST, user_id)
    if validation['success']:
        messages.add_message(
            request,
            messages.INFO,
            'Description updated successfully',
            extra_tags = 'general')
    else:
        for error in validation['result']:
            messages.add_message(
                request,
                messages.ERROR,
                error,
                extra_tags = validation['from'])
    return redirect('dashboard:edit_user')

@_.if_not_POST('dashboard:dashboard')
def admin_remove_user(request, user_id):
    User.objects.remove_user(user_id)
    return redirect('dashboard:dashboard')
@_.if_not_POST('dashboard:dashboard')
def admin_edit_user(request, user_id):
    user = User.objects.get(id = user_id)
    if user.privileges != 0:
        return redirect('dashboard:dashboard')
    context = {
        'user' : user
    }
    return render(request, 'user_dashboard/admin_edit_user.html', context)

apps/user_dashboard/templates/user_dashboard/admin_edit_user.html
{% extends 'user_dashboard/base.html' %}
{% block title %}Edit {{user.first_name}}{% endblock %}
{% block main %}
<div class="row">
	<div class="nine columns">
		<h1>Edit user #{{user.id}}</h1>
	</div>
	<div class="three columns">
		<a href="{% url 'dashboard:dashboard' %}">Return to Dashboard</a>
	</div>
</div>
<div class="row">
	<div class="six columns">
		<h3>Edit Information</h3>
		<ul id="info-errors">
		<form action="{% url 'dashboard:edit_info_process' user_id=user.id %}" method="POST">
			{% csrf_token %}
			<label for="email">E-Mail Address</label>
			<input name="email" type="text" value="{{user.email}}">
			<label for="first_name">First Name:</label>
			<input name="first_name" type="text" value="{{user.first_name}}">
			<label for="last_name">Last Name</label>
			<input name="last_name" type="text" value="{{user.last_name}}">
			<label for="privileges">User Privileges</label>
			<select name="privileges">
				<option value="0">Normal</option>
				<option value="9">Admin</option>
			</select>
			<button type="submit">Update</button>
		</form>
	</div>
	<div class="six columns">
	
	</div>
</div>
{% endblock %}

apps/user_dashboard/templates/user_dashboard/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %} {% endblock %}</title>
		<meta charset="utf-8">
		<meta name="description" content="{% block description %} {% endblock %}">
		{% load static %}
		<link rel="stylesheet" href="{% static 'user_dashboard/css/normalize.css' %}">
		<link rel="stylesheet" href="{% static 'user_dashboard/css/skeleton.css' %}">
		<link rel="stylesheet" href="{% static 'user_dashboard/css/style.css' %}">
		{% block extra_styles %}{% endblock %}
	</head>
	<body>
		<nav id="nav">
			<div class="container">
			{% block nav %}
				<div class="row">
					<div class="two columns">
						<span>MyApps</span>
					</div>
					{% if request.session.current_user_id %}
					<div class="two columns">
						<span><a href="{% url 'dashboard:dashboard' %}">Dashboard</a></span>
					</div>
					<div class="two columns">
						<span><a href="{% url 'dashboard:edit_user' %}">Edit Profile</a></span>
					</div>
					{% else %}
					<div class="two columns">
						<span><a href="{% url 'dashboard:index' %}">Home</a></span>
					</div>
					{% endif %}
					{% if request.session.current_user_id %}
					<div class="two offset-by-four columns">
						<span><a href="{% url 'dashboard:signout' %}">Logout</a></span>
					</div>
					{% else %}
					<div class="two offset-by-six columns">
						<span><a href="{% url 'dashboard:signin' %}">Sign in</a></span>
					</div>
					{% endif %}

				</div>
			{% endblock %}
			</div>
		</nav>
		<div id="main">
			<div class="container">
			{% block main %}
			{% endblock %}
			</div>
		</div>
		<div id="footer">
			<div class="container">
			{% block footer %}
			<span>User Dashboard 2017</span>
			{% endblock %} 
			</div>
		</div>
	</body>
</html>

apps/user_dashboard/templates/user_dashboard/dashboard.html
{% extends 'user_dashboard/base.html' %}

{% block title %}Dashboard{% endblock %}
{% block description %}Dashboard page for users{% endblock %}
{% block main %}
{% with is_admin=request.session.current_user_is_admin %}
{% if is_admin %}
<div class="row">
	<div class="four columns">
		<h1>Manage Users</h1>
	</div>
	<div class="two offset-by-six columns">
		<form action="{% url 'dashboard:new_user' %}" method="POST">
			{% csrf_token %}
			<button type="submit">Add user</button>
		</form>
	</div>
</div>
{% else %}
<div class="row">
	<div class="four columns">
		<h1>All Users</h1>
	</div>
</div>
{% endif %}
<div class="row">
	<!-- make this table responsive eventually -->
	<table id="responisve-table">
		<thead>
			<td>ID</td>
			<td>Name</td>
			<td>E-Mail</td>
			<td>Join Date</td>
			<td>Privileges</td>
			<td>Active</td>
			<td>Visible</td>
			{% if is_admin %}
			<td>actions</td>
			{% endif %}
		</thead>
		<tbody>
			{% load tz %}
			{% timezone "America/Los_Angeles" %}
			{% for user in users %}
			<tr>
				<td>{{user.id}}</td>
				<td>
					<a href="{% url 'messages:show_user' user_id=user.id %}">
						{{user.first_name}} {{user.last_name}}
					</a>
				</td>
				<td>{{user.email}}</td>
				<td>{{user.created_at}}</td>
				<td>{{user.privileges}}</td>
				<td>{{user.is_active}}</td>
				<td>{{user.is_visible}}</td>
				{% if is_admin %}
				{% if user.privileges == 0 %}
				<td>	
					<form action="{% url 'dashboard:admin_edit_user' user_id=user.id %}" method="POST">
						{% csrf_token %}
						<button type="submit">Edit</button>
					</form>
					{% if user.is_active %}	
					<form action="{% url 'dashboard:admin_remove_user' user_id=user.id %}" method="POST">
						{% csrf_token %}
						<button type="submit">Remove</button>
					</form>
					{% endif %}
				</td>
				{% else %}
				<td>Unavailable</td>
				{% endif %}
				{% endif %}
			</tr>
			{% endfor %}
			{% endtimezone %}
		</tbody>
	</table>
</div>
{% endwith %}
{% endblock %}

apps/user_dashboard/templates/user_dashboard/edit_user.html
{% extends 'user_dashboard/base.html' %}
{% block title %}Edit your profile{% endblock %}
{% block description %}Form for editing the current user's data.{% endblock %}
{% block main %}
{% with u_id=request.session.current_user_id %}
<div class="row">
	<div class="twelve columns">
		<h1>Edit Profile</h1>
		<ul id="general-messages">
		{% if messages %}
		{% for message in messages %}
		{% if message.extra_tags == 'general' %}
			<li>{{message}}</li>
		{% endif %}
		{% endfor %}
		{% endif %}
		</ul>
	</div>
</div>
<div class="row">
	<div class="six columns">
		<h2>Edit information</h2>
		<ul id="info-errors">
		{% if messages %}
		{% for message in messages %}
		{% if message.extra_tags == 'info' %}
			<li>{{message}}</li>
		{% endif %}
		{% endfor %}
		{% endif %}
		</ul>
		<form action="{% url 'dashboard:edit_info_process' user_id=u_id %}" method="POST">
			{% csrf_token %}
			<label for="first_name">First Name:</label>
			<input name="first_name" type="text" value="{{user.first_name}}">
			<label for="last_name">Last Name:</label>
			<input name="last_name" type="text" value="{{user.last_name}}">
			<label for="email">E-Mail Address</label>
			<input name="email" type="text" value="{{user.email}}">
			<button type="submit">Save</button>
		</form>
	</div>
	<div class="six columns">
		<h2>Update Password</h2>
		<ul id="password-errors">
		{% if messages %}
		{% for message in messages %}
		{% if message.extra_tags == 'password' %}
			<li>{{message}}</li>
		{% endif %}
		{% endfor %}
		{% endif %}
		</ul>
		<form action="{% url 'dashboard:edit_password_process' user_id=u_id %}" method="POST">
			{% csrf_token %}
			<label for="password">New Password:</label>
			<input name="password" type="password">
			<label for="password_confirm">Confirm New Password:</label>
			<input name="password_confirm" type="password">
			<button type="submit">Update</button>
		</form>
	</div>
</div>
<div class="row">
	<div class="six columns">
		<h2>Update Description</h2>
		<ul id="description-errors">
		{% if messages %}
		{% for message in messages %}
		{% if message.extra_tags == 'description' %}
			<li>{{message}}</li>
		{% endif %}
		{% endfor %}
		{% endif %}
		</ul>
		<form action="{% url 'dashboard:edit_description_process' user_id=u_id %}" method="POST">
			{% csrf_token %}
			<label for="description">Edit description:</label>
			<textarea name="description" placeholder="{{user.description}}"></textarea>
			<button type="submit">Save</button>
		</form>
	</div>
</div>
{% endwith %}
{% endblock %}

apps/user_dashboard/templates/user_dashboard/index.html
{% extends 'user_dashboard/base.html' %}
{% block title %}Home{% endblock %}
{% block description %}Our app starts here{% endblock %}
{% block main %}
<div class="row">
	<h1>Welcome</h1>
	<p>
	We're going to build a cool application using a MVC framework!
	This application was built during the Coding Dojo 2017 February cohort!
	</p>
	<a href="{% url 'dashboard:signin' %}">Start</a>
</div>
<div class="row">
	<div class="one-third column">
		<h4>Manage Users</h4>
		<p>
			Using this application, you'll be able to add,
			remove, and edit users of this application.
		</p>
	</div>
	<div class="one-third column">
		<h4>Leave Messages</h4>
		<p>
			Users will be able to leave a message for
			another user in this application
		</p>
	</div>
	<div class="one-third column">
		<h4>Edit user information</h4>
		<p>
			Admins will be able to edit another user's
			information (email adress, first name, last name.
		</p>
	</div>
</div>
{% endblock %}

apps/user_dashboard/templates/user_dashboard/new_user.html
{% extends 'user_dashboard/base.html' %}
{% block title %}Add a New User{% endblock %}
{% block description %}Admin only page for creating new users{% endblock %}
{% block main %}
<div class="row">
	<div class="four columns">
		<h1>Add New User</h1>
		{% if messages %}
		<ul id="messages">
		{% for message in messages %}
			<li>{{message}}
		{% endfor %}
		</ul>
		{% endif %}
		<form action="{% url 'dashboard:user_new_process' %}" method="POST">
			{% csrf_token %}
			<label for="first_name">First Name:</label>
			<input name="first_name" type="text">
			<label for="last_name">Last Name:</label>
			<input name="last_name" type="text">
			<label for="email">E-Mail Address:</label>
			<input name="email" type="text">
			<label for="password">Password:</label>
			<input name="password" type="password">
			<label for="password_confirm">Confirm Password:</label>
			<input name="password_confirm" type="password">
			<label for="privileges">User Privileges:</label>	
			<select name="privileges">
				<option value="admin">Administrator</option>
				<option value="normal">Normal</option>
			</select>
			<button type="submit">Create</button>
		</form>
	</div>
	<div class="two offset-by-six columns">
		<a href="{% url 'dashboard:dashboard' %}">Return to Dashboard</a>
	</div>
</div>
{% endblock %}

apps/user_dashboard/templates/user_dashboard/register.html
{% extends 'user_dashboard/base.html' %}
{% block title %}Register{% endblock %}
{% block description %}Registration page{% endblock %}
{% block main %}
<div class="row">
	<div id="form-container" class="one-third column">
		<h5>Register</h5>
		{% if messages %}
		<ul id="registration-errors">
			{% for message in messages %}
			{% if message.extra_tags == 'register' %}
			<li>{{message}}</li>
			{% endif %}
			{% endfor %}
		</ul>
		{% endif %}
		<form action="{% url 'dashboard:register_process' %}" method="POST">
			{% csrf_token %}
			<label  for="first_name">First Name:</label>
			<input name="first_name" type="text">
			<label  for="last_name">Last Name:</label>
			<input name="last_name" type="text">
			<label  for="email">E-Mail Address</label>
			<input name="email" type="text">
			<label  for="password">Password:</label>
			<input name="password" type="password">
			<label  for="password_confirm">Confirm Password:</label>
			<input name="password_confirm" type="password">
			<button type="submit">Register</button>
		</form>
	</div>
</div>
{% endblock %}

apps/user_dashboard/templates/user_dashboard/signin.html
{% extends 'user_dashboard/base.html' %}
{% block title %}Sign In{% endblock %}
{% block description %}Sign in page for our app{% endblock %}
{% block main %}
<div class="row">
	<div id="form-container" class="one-third column">
		<h5>Sign In</h5>
		{% if messages %}
		<ul>
		{% for message in messages %}
			<li>{{message}}</li>
		{% endfor %}
		</ul>
		{% endif %}
		<form action="{% url 'dashboard:signin_process' %}" method="POST">
			{% csrf_token %}
			<label for="email">E-Mail Address</label>
			<input type="text" name="email">
			<label for="password">Password</label>
			<input name="password" type="password">
			<button type="submit">Sign In!</button>
		</form>
		<a href="{% url 'dashboard:register' %}">Don't have an account? Register here</a>
	</div>
</div>
{% endblock %}

apps/user_dashboard/templates/user_dashboard/signout.html
{% extends 'user_dashboard/base.html' %}
{% block title %}Signed Out{% endblock %}
{% block description %}Sign out confirmation page{% endblock %}
{% block main %}
<h1>Signed out</h1>
<p>Come back soon!</p>
{% endblock %}